name: inventory_management_app_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  file_picker: ^9.0.2
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  printing: ^5.14.2
  realm: ^20.0.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  syncfusion_flutter_xlsio: ^28.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
